baseURL = "https://blog.gramila.dev"
languageCode = "en-us"
title = "John G Blog"
theme = "base"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  description = "Hello internet wanderer. We pray you find entertainment, then peace."
  title = "John G Blog"
  author = "John Gramila"
  imageSizes = "1280 768 640 320"
  imageFormats = "webp jpeg"
